routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', function () {
    return view('home');
});

// Route::get('/master', function(){
//     return view('adminlte.master');
// });

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/genre', 'GenreController');
    Route::resource('profile', 'ProfileController')->only([
        'index', 'update'
    ]);
    Route::resource('/answer', 'AnswerController')->only([
        'store'
    ]);
});

Route::resource('/question', 'QuestionController');

Auth::routes();

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $table = "answers";
    protected $fillable = ['answer', 'questions_id'];


    public function user()
    {
        return $this->belongsTo('App\User', 'users_id');
    }

    public function question()
    {
        return $this->belongsTo('App\Question', 'questions_id');
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Answer;
use App\Question;
use Illuminate\Support\Facades\Auth;

class AnswerController extends Controller
{
    public function create(){
      
    }

    public function store(Request $request){
        $request->validate([
            'answer' => 'required',
        ]);
    

      
         $answer = new Answer;
         $answer->users_id = Auth::id();
         $answer->questions_id = $request->questions_id;
         $answer->answer = $request->answer;
         

         $answer->save();

         return redirect()->back();
        }

        public function index() {
        
        }

        public function show($id){
            
        }

        public function edit($id) {
            
        }

        // public function update($id, Request $request){
           
        // }

        public function destroy($id){
          
        }
}

resources/views/answer/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="ml-3 mt-3">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create New Answer</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/answer" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="answer">Answer</label>
                    <input type="text" class="form-control" id="answer" name="answer" value=" {{ old('answer', '')}}" placeholder="Enter Answer">
                    @error('answer')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                
                <div class="form-group">
                <label>Question</label>
                <select id="questions_id" name="questions_id" class="form-control">                    					
				          <option value="">--Silahkan Pilih Genre--</option>
                  @foreach ($question as $item)
                    <option value="{{$item->id}}">{{$item->answer}}</option>
                  @endforeach
                  </select>
                  @error('questions_id')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                 </div>
                 
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </form>
            </div>

</div>

@endsection

resources/views/answer/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="ml-3 mt-3">
<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit answer {{ $question -> id }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/answer" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="answer">Answer</label>
                    <input type="text" class="form-control" id="answer" name="answer" value=" {{ old('title', $question->title) }}" placeholder="Enter Answer">
                    @error('answer')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>

              <div class="form-group">
                <label>Question</label>
                <select id="questions_id" name="questions_id" class="form-control">                   					
				          <option value="">--Silahkan Pilih Question--</option>
                  @foreach ($question as $item)
                  @if ($item->id === $answer->questions_id)
                  <option value="{{$item->id}}" selected>{{$item->title}}</option>
                  @else
                    <option value="{{$item->id}}">{{$item->title}}</option>
                  @endif
                  @endforeach
                  </select>
                  @error('questions_id')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </form>
            </div>

</div>

@endsection

resources/views/answer/index.blade.php
@extends ('adminlte.master')

@section('content')
    <div class="mt-3 ml-3">
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Question Table</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                  @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                  @endif
                  <a class="btn btn-primary mb-2" href="/answer/create">Create New answer</a>
                <table class="table table-bordered">
                  <thead>                  
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>Answer</th>
                      <th>Question</th>
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                   @forelse($answer as $key => $answer)
                    <tr>
                        <td> {{ $key + 1 }} </td>
                        <td> {{ $answer->answer }} </td>
                        <td> {{ $answer->questions_id }} </td>
                    
                        <td style="display: flex;">
                            <a href=" {{ route('answer.show', ['answer' => $answer->id])}} " class="btn btn-info btn-sm">Show</a>
                            <a href="/answer/{{ $answer->id}}/edit" class="btn btn-default btn-sm">Edit</a>
                           <form action="/answer/{{ $answer->id}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="submit" value="delete" class="btn btn-danger btn-sm">
                           </form>
                        
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" align="center">No Question</td>
                    </tr>
                    
                   @endforelse
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
          
            </div>
    </div>
@endsection

resources/views/answer/show.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-3">
    <h4> {{ $answer->answer}} </h4>
</div>
   
@endsection